#!/usr/bin/env python3
# Auto-generated configuration module
# Edit the lambda functions below to define the vector field for each region

import numpy as np


def define_region_functions():
    """Define vector field for each region (autogenerated)."""
    return {
        'dot': lambda x, y, z: np.array([1, 0, 0]),
    }
