#!/usr/bin/env python3
# Auto-generated configuration module
# Edit the lambda functions below to define magnetization vector field for each region

import numpy as np


def define_region_functions():
    """Define magnetization vector field for each region (autogenerated)."""
    return {
        'sphere_volume': lambda x, y, z: [-y, x, 0],
    }
